### ISSUE TITLE
0.1.0 설치 이슈 목록

### ISSUE THREAD

**Issue by crack-love** [crack-love/KSL#12]
## issue
- 개발환경 vc15(visual studio 2017)로 통일
- dll 파일 실행파일 위치에 포함

## todo
- [x] Visual studio 15 (2017) 이용 명시
- [x] 바이너리 파일 실행시 dll 5개 이용 가능토록
- [ ] 키넥트 미연결시 오류 출력
- [x] https://www.microsoft.com/en-us/download/details.aspx?id=44559

## note
- vc14 이용 컴파일 시 '빌드 v141'이 필요하다는 오류는 vc15 설치가 꼭 필요하다
- dll 목록
  - kinect20.dll
  - kinect20.face.dll
  - opencv_world341.dll
  - opencv_world341d.dll
  - msvcr110.dll
  - msvcp110.dll

**Comment by crack-love** [comment]
이 설치 이슈는  0.1.0버전에 해당 0.2.0버전은 모두 해결했습니다
