### ISSUE TITLE
Milestone 20180605

### ISSUE THREAD

**Issue by crack-love** [crack-love/KSL#18]
- [ ] 핸드 ROI로 정확도 상승
- [ ] 다양한 단어 조합 (손가락 차이 구분)
- [ ] RNN | LSTM 시도
